Repository LikeLion-team14/grooveo, pull requests merged in 2023-07, with the labels that each got.

#94 UserDetailsService 디렉토리 이동 (config) / yml 수정
  src/main/java/com/kl/grooveo/base/security/CustomUserDetailsService.java
  src/main/java/com/kl/grooveo/boundedContext/member/service/MemberSecurityService.java
  src/main/resources/application.yml
Labels: 🐿 refactor, 🦉 documentation

#96 FreedomPost 관심사 분리(DTO)
  src/main/java/com/kl/grooveo/boundedContext/comment/controller/FreedomPostCommentController.java
  src/main/java/com/kl/grooveo/boundedContext/comment/controller/SoundPostCommentController.java
  src/main/java/com/kl/grooveo/boundedContext/comment/dto/CommentFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/community/controller/FreedomPostController.java
  src/main/java/com/kl/grooveo/boundedContext/community/dto/FreedomPostDTO.java
  src/main/java/com/kl/grooveo/boundedContext/community/dto/FreedomPostFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/community/entity/Category.java
  src/main/java/com/kl/grooveo/boundedContext/community/entity/FreedomPost.java
  src/main/java/com/kl/grooveo/boundedContext/community/repository/FreedomPostRepository.java
  src/main/java/com/kl/grooveo/boundedContext/community/service/FreedomPostService.java
  src/main/java/com/kl/grooveo/boundedContext/library/controller/FileUploadController.java
  src/main/java/com/kl/grooveo/boundedContext/library/controller/SoundTrackController.java
  src/main/java/com/kl/grooveo/boundedContext/library/dto/FileInfoFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/library/dto/SoundTrackFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/reply/controller/FreedomPostReplyController.java
  src/main/java/com/kl/grooveo/boundedContext/reply/controller/SoundPostReplyController.java
  src/main/java/com/kl/grooveo/boundedContext/reply/dto/ReplyFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/thumbsUp/controller/SoundThumbsUpController.java
  src/main/java/com/kl/grooveo/boundedContext/thumbsUp/controller/ThumbsUpController.java
  src/main/java/com/kl/grooveo/boundedContext/thumbsUp/dto/ThumbsUpDTO.java
  src/main/java/com/kl/grooveo/boundedContext/thumbsUp/service/SoundThumbsUp_summaryService.java
  src/main/java/com/kl/grooveo/boundedContext/thumbsUp/service/ThumbsUp_summaryService.java
  src/main/resources/application.yml
  src/main/resources/templates/usr/community/freedomPost/detail.html
  src/main/resources/templates/usr/community/freedomPost/form.html
  src/main/resources/templates/usr/community/freedomPost/list.html
Labels: 🐥 fix, 🐿 refactor

#97 application.yml에 baseUrl 추가
  src/main/resources/application.yml
Labels: 🦍 setting

#98 Member 관심사 분리(DTO)
  src/main/java/com/kl/grooveo/boundedContext/member/controller/MemberController.java
  src/main/java/com/kl/grooveo/boundedContext/member/dto/FindPasswordFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/member/dto/FindUsernameFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/member/dto/JoinFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/member/dto/ModifyEmailFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/member/dto/ModifyNickNameFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/member/dto/ModifyPasswordFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/member/form/FindUsernameForm.java
  src/main/java/com/kl/grooveo/boundedContext/member/service/MemberService.java
Labels: 🐿 refactor

#100 음원 등록 UI 수정
  src/main/java/com/kl/grooveo/boundedContext/library/controller/SoundTrackController.java
  src/main/resources/templates/usr/library/soundDetail.html
  src/main/resources/templates/usr/library/soundUpload.html
Labels: 🦚 view

#99 FileInfo 관심사 분리(DTO) / FileInfo 리펙토링
  src/main/java/com/kl/grooveo/boundedContext/home/controller/MainController.java
  src/main/java/com/kl/grooveo/boundedContext/library/controller/FileUploadController.java
  src/main/java/com/kl/grooveo/boundedContext/library/controller/SoundTrackController.java
  src/main/java/com/kl/grooveo/boundedContext/library/dto/FileInfoDTO.java
  src/main/java/com/kl/grooveo/boundedContext/library/dto/FileInfoFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/library/dto/SoundTrackFormDTO.java
  src/main/java/com/kl/grooveo/boundedContext/library/entity/FileInfo.java
  src/main/java/com/kl/grooveo/boundedContext/library/service/FileInfoService.java
  src/main/java/com/kl/grooveo/boundedContext/library/service/SoundTrackService.java
  src/main/resources/templates/usr/home/main.html
Labels: 🐿 refactor, 🦚 view

#101 PR 템플릿 적용
  .github/pull_request_template.md
Labels: 🦍 setting
